### ISSUE TITLE
Exogenous Variables and adding Lags with Lazy Prophet

### ISSUE THREAD

**Issue by cloudymcrob** [tblume1992/LazyProphet#1]
Hi Tyler, cool looking package! I'm trying to give it a whirl but can't seem to find any documentation explaining how to use exogenous variables with the LazyProphet model, or how to include lagged features. There is a mention of exogenous features in the V0.1 description, but can't find anything else. Would be interested to know how to use the mentioned features, thanks!

**Comment by tblume1992** [comment]
Yeah I have documentation strewn across the internet I definitely need to consolidate. There is an example [gist ](https://gist.github.com/tblume1992/bde67aa7a12ab7307fc4913dd5a5f912) of using exogenous data. Pretty simple, just pass it to fit and then to predict. When passing exogenous, I would stick to 2d arrays with size (n, k) where n is the number of observations and k is the number of variables. Just be aware of sizes, your n when passing to predict needs to be the same as the forecast horizon and the k must be the same always.

For lagged features you have two parameters in the init:

1. `ar` - which accepts a list of lags to create so passing `[1, 2, 3,]` will create a variable that uses the last 1 value, a separate variable that looks at 2 values ago, and another variable that looks at the value 3 periods ago. Then in the forecast period the last predicted point is used if needed. 

2. `ma_windows` - works the same as ar but for moving average, so `[4, 6]` is a moving average using a window of the last 4 values and another variable that uses the last 6 values. I wouldn't use ma_windows though as the results are very wonky, either it doesn't play well with the basis functions (which is at the core of the model) or there is a bug.

IF you want lagged features of variables in your exogenous you will have to create that on your own and pass them.

For some more documentation I have a few medium articles covering various things about the model:

1.  [Time Series Forecasting with LazyProphet](https://medium.com/p/3745bafe5ce5)
2. [Time Series Classification with LazyProphet](https://medium.com/p/d79d2d81bfd0)
3. [Handling Trends in Time Series with Tree Models](https://medium.com/p/fea5e4c066fb)

**Comment by cloudymcrob** [comment]
Thanks for the quick reply, that got it working! Perhaps using the same format as sklearn and calling the exogenous variable argument "X" in both the fitting and predicting methods would be a little clearer?

**Comment by tblume1992** [comment]
Awesome, glad you got it working.

Yeah that could definitely be added as an alias, the early design was built around Facebook Prophet so that is where the future part comes from.
