### ISSUE TITLE
Citation Consulting

### ISSUE THREAD

**Issue by Cyue0316** [tblume1992/LazyProphet#2]
Hi, I have used LazyProphet in my thesis manuscript and I think it is a very fascinating work. But I have a problem, I want to cite in the article, but I can't seem to find a suitable way to cite it. Could you please provide a way to cite it if it is convenient for you? Also, can you provide some formulaic introduction to the model?

**Comment by tblume1992** [comment]
Glad you enjoy the package! I went ahead and added a citation file which creates ctiations for you on the homepage of the package which should be good enough: 
![image](https://user-images.githubusercontent.com/25492419/182031892-343e9614-05d3-4638-97f1-88bfc624c80e.png)

In terms of a formulaic description I don't have anything handy and it would depend on what features you are using. At the core of the model is LightGBM which has some great [documentation ](https://proceedings.neurips.cc/paper/2017/file/6449f44a102fde848669bdd9eb6b76fa-Paper.pdf)you could reference.

And for features it really is just fourier basis functions for seasonality which you can grab the formulaic description from page 11 of Prophet's [paper](https://peerj.com/preprints/3190.pdf). 

The trend piece depends on what you are using, if `weighted=False` then this is just using peicewise linear basis functions, you can find a description about halfway down this [page](http://hplgit.github.io/INF5620/doc/pub/sphinx-fem/._main_fem003.html).

If `weighted=True` then you are using a 'weighted' piecewise linear basis function which are simply a line from the first point to a 'middle' point and the final point in the series. Where the middle point is determined by `n_basis`. If `n_basis=5` then you will have 5 evenly spaced 'middle' points.

Here is a quick illustration:
![image](https://user-images.githubusercontent.com/25492419/182033171-08a88279-f388-4716-9d49-f337e4e0cf53.png)

Hope this helps! Let me know if you want any help implementation or parameter settings!

**Comment by Harry040** [comment]
I think these "piece feature" has Look-ahead bias (aka future function), That's right? @tblume1992

**Comment by tblume1992** [comment]
@Harry040 the functions use the whole series provided to build the features so if you do not split your data **before** building the functions then it would have look-ahead bias same as scaling or using lags of your target.

For future prediction the functions are just projected forward without the need of the future data.

The only thing that ever introduces look-ahead bias is us ;)
